- variable tensors = generally used as matrices for storing weights & other informations, and are a **type of trainable data.**

- constant tensors are used as **variables for storing hyperparameters** or other structured data.

In [2]:
import tensorflow as tf

In [6]:
const_a = tf.constant([[1,2, 3, 4]], shape=[2,2], dtype=tf.float32)
const_a

# common constant attributes
print("shape: ", const_a.shape) 
print("data type: ", const_a.dtype) 
print("value: ", const_a.numpy())

shape:  (2, 2)
data type:  <dtype: 'float32'>
value:  [[1. 2.]
 [3. 4.]]


In [12]:
zeros_b = tf.zeros([3,5], dtype=tf.float32)
zeros_b

zeros_like_b = tf.zeros_like(const_a) # create zeroes with attributes like const_a
zeros_like_b.numpy()

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [15]:
fill_c = tf.fill([2,3], 9) # create a 2x3 matrix filled with 9s
fill_c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]])>

In [18]:
random_e = tf.random.normal([2,3], mean=0, stddev=1, seed=1) # create a 2x3 matrix filled with random numbers
random_e.numpy()

array([[ 0.4291683 ,  0.03209855,  0.11945234],
       [-1.552837  , -1.529219  ,  0.12525094]], dtype=float32)

In [22]:
# convert value to tensor
my_list = [1,2,3,4,5,6,7,8,9,10]
tensor_list = tf.convert_to_tensor(my_list, dtype=tf.float32)
tensor_list

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)>

In [26]:
# creating variable tensor
var_a = tf.Variable(tf.ones([2,2]), dtype=tf.float32)
var_a


<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>