# Tensor
Dalam TensorFlow, tensor terklasifikasi menjadi **tensor konstan** dan **tensor variable**
- tensor konstan = tensor yang nilai dan dimensinya tidak bisa diubah-ubah. tensor konstan biasa digunakan untuk menyimpan hyperparameter.

- variable tensor = tensor yang value-nya bisa diubah, namun dimensinya tidak bisa diubah. variable tensor biasanya direpresentasikan sebagai matrix untuk menyimpan weights dan informasi lain. variable tensor juga merupakan tipe data yang dapat di-train (_trainable data_).


In [2]:
import tensorflow as tf

In [3]:
const_a = tf.constant([[1,2, 3, 4]], shape=[2,2], dtype=tf.float32)
const_a

# common constant attributes
print("shape: ", const_a.shape) 
print("data type: ", const_a.dtype) 
print("value: ", const_a.numpy())

shape:  (2, 2)
data type:  <dtype: 'float32'>
value:  [[1. 2.]
 [3. 4.]]


In [4]:
zeros_b = tf.zeros([3,5], dtype=tf.float32)
zeros_b

zeros_like_b = tf.zeros_like(const_a) # create zeroes with attributes like const_a
zeros_like_b.numpy()

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [5]:
fill_c = tf.fill([2,3], 9) # create a 2x3 matrix filled with 9s
fill_c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]])>

In [6]:
random_e = tf.random.normal([2,3], mean=0, stddev=1, seed=1) # create a 2x3 matrix filled with random numbers
random_e.numpy()

array([[-0.8113182 ,  1.4845988 ,  0.06532937],
       [-2.4427042 ,  0.0992484 ,  0.5912243 ]], dtype=float32)

In [7]:
# convert value to tensor
my_list = [1,2,3,4,5,6,7,8,9,10]
tensor_list = tf.convert_to_tensor(my_list, dtype=tf.float32)
tensor_list

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)>

In [8]:
# creating variable tensor
var_a = tf.Variable(tf.ones([2,2]), dtype=tf.float32)
var_a


<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [9]:
my_tensor = tf.random.normal([4,100,100,3])
my_tensor

# extract the first image
my_tensor[0,:,:,:]

# extract one slice at an interval of two imgs
my_tensor[::2,:,:,:] # or my_tensor[::2]

# slice data from the last element
my_tensor[-1,:,:,:] # or my_tensor[::-1]

<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
array([[[-5.9198022e-01, -7.6775628e-01, -5.0193805e-01],
        [-1.1309314e+00,  3.3112246e-01,  1.7204274e+00],
        [ 3.0965519e-01, -1.0130666e+00,  2.2829510e-01],
        ...,
        [-1.3092105e+00,  2.6306912e-01,  5.1721241e-02],
        [-3.1991130e-01, -7.7411965e-02, -5.8808494e-01],
        [ 1.3067348e-01, -3.0970109e-01,  1.5885645e+00]],

       [[ 3.3922918e-02, -1.0403768e+00,  9.3364352e-01],
        [-1.5429293e+00,  9.1013360e-01,  6.4618927e-01],
        [ 1.1929549e+00,  8.1612599e-01,  1.2023048e+00],
        ...,
        [ 3.2750383e-01, -1.3997563e+00,  3.4533975e-01],
        [ 3.0418736e-01, -1.8915264e-01,  5.4494017e-01],
        [ 9.1730618e-01, -2.3503714e+00, -1.5147152e+00]],

       [[-3.3456367e-02,  2.1049490e+00,  2.7709273e-01],
        [ 2.6709434e-02, -3.6667846e-04,  1.6176660e-01],
        [ 2.8057134e-01, -5.6067920e-01,  4.3588507e-01],
        ...,
        [ 1.2878704e-01, -8.3453

In [10]:
my_tensor[0][19][39][1]
indices = [0, 1, 3]
tf.gather(my_tensor, indices=indices, axis=0, batch_dims=0)

indices = [[0,1,1,0], [1,2,2,0]]
tf.gather_nd(my_tensor, indices=indices)



<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5280974 , 0.13820727], dtype=float32)>

In [11]:
# TENSOR DIMENSION MODIFICATION

const_d = tf.constant([[1,2,3,4], [5,6,7,8], [9,10,11,12]], dtype=tf.float32)

# there are three common methods for viewing a dimension
print("shape: ", const_d.shape)
print("shape: ", const_d.get_shape())


print("rank: ", const_d.ndim)
print("size: ", tf.size(const_d))

# test


shape:  (3, 4)
shape:  (3, 4)
rank:  2
size:  tf.Tensor(12, shape=(), dtype=int32)


in TF, a tensor has a both static (inferred) shape and a dynamic (true) shape.
The static shape can be read using `tf.Tensor.get_shape()` -> inferred from the operations that were used to create the tensor, but may be partially complete.

The dynamic shape can be read using `tf.Tensor.shape` -> the true shape of the tensor

In [12]:
reshape_d = tf.reshape(const_d, [2,6])
print(reshape_d)
tf.reshape(const_d, [2,6]).numpy()

tf.Tensor(
[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]], shape=(2, 6), dtype=float32)


array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]], dtype=float32)

### Dimensi tensor dapat diperbesar dengan `tf.expand_dims()` atau diperkecil dengan `tf.squeeze()`

In [18]:
expand_sample = tf.expand_dims(const_d, axis=0)
print(expand_sample) # add a dimension at the beginning
tf.expand_dims(const_d, axis=0).numpy()

squeeze_sample = tf.squeeze(expand_sample)
print(squeeze_sample) # remove the dimension at the beginning (from 1x3x4 to 3x4)


## --------------------- matrix transpose ---------------------
transpose_sample = tf.constant([[1,2,3,4], [5,6,7,8], [9,10,11,12]], dtype=tf.float32)
print("size of the original data: ", transpose_sample.shape)

transposed_sample = tf.transpose(transpose_sample)
print("size of the transposed data: ", transposed_sample.shape) # the matrix has transposed from 3x4 to 4x3



tf.Tensor(
[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]], shape=(1, 3, 4), dtype=float32)
tf.Tensor(
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]], shape=(3, 4), dtype=float32)
size of the original data:  (3, 4)
size of the transposed data:  (4, 3)



## Broadcasting
- cara untuk melakukan operasi pada tensor pada shapes yang berbeda-beda
- tensor yang lebih kecil _di-broadcast_ untuk menyamakan bentuk tensor yang lebih besar

`tf.broadcast_to()` = broadcast data dari dimensi kecil ke dimensi yang besar

In [25]:
broadcast_sample = tf.constant([[1,2,3,4,5,6]]) # create a 1x6 matrix
print("original data: ", broadcast_sample.numpy())

broadcasted_sample = tf.broadcast_to(broadcast_sample, shape=[4,6]) # change the shape to 4x6
print("broadcasted data: ", broadcasted_sample.numpy) # the matrix has transposed from 3x4 to 4x3

original data:  [[1 2 3 4 5 6]]
broadcasted data:  <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])>>
