# Tensor
Dalam TensorFlow, tensor terklasifikasi menjadi **tensor konstan** dan **tensor variable**
- tensor konstan = tensor yang nilai dan dimensinya tidak bisa diubah-ubah. tensor konstan biasa digunakan untuk menyimpan hyperparameter.

- variable tensor = tensor yang value-nya bisa diubah, namun dimensinya tidak bisa diubah. variable tensor biasanya direpresentasikan sebagai matrix untuk menyimpan weights dan informasi lain. variable tensor juga merupakan tipe data yang dapat di-train (_trainable data_).


In [2]:
import tensorflow as tf

In [6]:
const_a = tf.constant([[1,2, 3, 4]], shape=[2,2], dtype=tf.float32)
const_a

# common constant attributes
print("shape: ", const_a.shape) 
print("data type: ", const_a.dtype) 
print("value: ", const_a.numpy())

shape:  (2, 2)
data type:  <dtype: 'float32'>
value:  [[1. 2.]
 [3. 4.]]


In [12]:
zeros_b = tf.zeros([3,5], dtype=tf.float32)
zeros_b

zeros_like_b = tf.zeros_like(const_a) # create zeroes with attributes like const_a
zeros_like_b.numpy()

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [15]:
fill_c = tf.fill([2,3], 9) # create a 2x3 matrix filled with 9s
fill_c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 9, 9],
       [9, 9, 9]])>

In [18]:
random_e = tf.random.normal([2,3], mean=0, stddev=1, seed=1) # create a 2x3 matrix filled with random numbers
random_e.numpy()

array([[ 0.4291683 ,  0.03209855,  0.11945234],
       [-1.552837  , -1.529219  ,  0.12525094]], dtype=float32)

In [22]:
# convert value to tensor
my_list = [1,2,3,4,5,6,7,8,9,10]
tensor_list = tf.convert_to_tensor(my_list, dtype=tf.float32)
tensor_list

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)>

In [26]:
# creating variable tensor
var_a = tf.Variable(tf.ones([2,2]), dtype=tf.float32)
var_a


<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [29]:
my_tensor = tf.random.normal([4,100,100,3])
my_tensor

# extract the first image
my_tensor[0,:,:,:]

# extract one slice at an interval of two imgs
my_tensor[::2,:,:,:] # or my_tensor[::2]

# slice data from the last element
my_tensor[-1,:,:,:] # or my_tensor[::-1]

<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
array([[[-1.18719065e+00, -2.63436377e-01, -1.52620959e+00],
        [ 1.30696321e+00, -4.24901694e-01,  4.89547729e-01],
        [-7.94782769e-03,  4.36548769e-01, -1.72637093e+00],
        ...,
        [ 2.12353063e+00, -3.76383752e-01,  1.39547810e-01],
        [-1.73320577e-01,  8.88793647e-01,  9.79248211e-02],
        [ 1.09435272e+00,  9.09661651e-01, -5.66842675e-01]],

       [[-2.77779818e-01,  2.75303304e-01,  6.35645986e-01],
        [ 2.28012470e-03, -1.20523250e+00,  5.39059676e-02],
        [-1.06216706e-01,  4.58525345e-02, -1.18232083e+00],
        ...,
        [ 1.86671838e-01, -1.96268129e+00, -2.20672083e+00],
        [-3.36997986e-01,  4.60574806e-01,  3.06418324e+00],
        [-6.18160129e-01,  1.81018651e+00,  1.04465508e+00]],

       [[-1.95649695e+00, -1.18814826e+00,  3.59745532e-01],
        [-1.08861196e+00,  1.21214747e+00, -3.25597554e-01],
        [-3.56437773e-01, -3.05301160e-01, -6.42887414e-01],


In [32]:
my_tensor[0][19][39][1]
indices = [0, 1, 3]
tf.gather(my_tensor, indices=indices, axis=0, batch_dims=0)

indices = [[0,1,1,0], [1,2,2,0]]
tf.gather_nd(my_tensor, indices=indices)



<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.88494915,  0.00523869], dtype=float32)>

In [34]:
# TENSOR DIMENSION MODIFICATION

const_d = tf.constant([[1,2,3,4], [5,6,7,8], [9,10,11,12]], dtype=tf.float32)

# there are three common methods for viewing a dimension
print("shape: ", const_d.shape)
print("shape: ", const_d.get_shape())


print("rank: ", const_d.ndim)
print("size: ", tf.size(const_d))

# test


shape:  (3, 4)
shape:  (3, 4)
rank:  2
size:  tf.Tensor(12, shape=(), dtype=int32)


in TF, a tensor has a both static (inferred) shape and a dynamic (true) shape.
The static shape can be read using `tf.Tensor.get_shape()` -> inferred from the operations that were used to create the tensor, but may be partially complete.

The dynamic shape can be read using `tf.Tensor.shape` -> the true shape of the tensor

In [37]:
reshape_d = tf.reshape(const_d, [2,6])
print(reshape_d)
tf.reshape(const_d, [2,6]).numpy()

tf.Tensor(
[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]], shape=(2, 6), dtype=float32)


array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]], dtype=float32)